# config
cover: /img/skulls.png
logo: /img/profile.png
bio: 'Edgar is a developer, father, husband and technology enthusiast. He likes to write about technology, work-life balance and eventually even some fiction.'

# Content
excerpt_link: Read More

# Miscellaneous
rss:
